// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.5         [198917]
ROOT Release   : 5.22/00       [333312]
Creator        : govoni
Date           : Wed Mar  4 22:12:14 2009
Host           : Darwin pb-d-128-141-34-27.cern.ch 9.6.0 Darwin Kernel Version 9.6.0: Mon Nov 24 17:37:00 PST 2008; root:xnu-1228.9.59~1/RELEASE_I386 i386
Dir            : /Users/govoni/private/job/learn/root/TMVA/testTMVA
Training events: 1630


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
vars.Deta                     vars.Deta                         'F'    [0.00154621631373,9.01126003265]
vars.Dphi                     vars.Dphi                         'F'    [0.000456965295598,3.14073491096]
vars.Minv                     vars.Minv                         'F'    [13.3289089203,3685.25610352]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fStatusIsClean( true ),
        fNvars( 3 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "vars.Deta", "vars.Dphi", "vars.Minv" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.0015462163137272;
      fVmax[0] = 9.01126003265381;
      fVmin[1] = 0.000456965295597911;
      fVmax[1] = 3.14073491096497;
      fVmin[2] = 13.3289089202881;
      fVmax[2] = 3685.25610351562;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[5][4];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[4][5];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][4];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 4; fWeights[0] = new double[4]; 
   fLayerSize[1] = 5; fWeights[1] = new double[5]; 
   fLayerSize[2] = 4; fWeights[2] = new double[4]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.31028429773678;
   fWeightMatrix0to1[1][0] = 3.01265837463956;
   fWeightMatrix0to1[2][0] = 2.30850257051772;
   fWeightMatrix0to1[3][0] = 1.01430838433069;
   fWeightMatrix0to1[0][1] = 0.334857537625069;
   fWeightMatrix0to1[1][1] = -0.540605415915559;
   fWeightMatrix0to1[2][1] = -0.794204745352753;
   fWeightMatrix0to1[3][1] = 1.69165238350358;
   fWeightMatrix0to1[0][2] = -3.72343421405098;
   fWeightMatrix0to1[1][2] = -0.800145980752251;
   fWeightMatrix0to1[2][2] = -2.44382581813696;
   fWeightMatrix0to1[3][2] = 0.0384875756912746;
   fWeightMatrix0to1[0][3] = -3.35654758253875;
   fWeightMatrix0to1[1][3] = 1.58963568663627;
   fWeightMatrix0to1[2][3] = -1.87705570903934;
   fWeightMatrix0to1[3][3] = -0.652334347611153;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.42750487744022;
   fWeightMatrix1to2[1][0] = 1.63972927903216;
   fWeightMatrix1to2[2][0] = 0.188915587052553;
   fWeightMatrix1to2[0][1] = 1.50705068540617;
   fWeightMatrix1to2[1][1] = -0.180804151273297;
   fWeightMatrix1to2[2][1] = -1.32994439845902;
   fWeightMatrix1to2[0][2] = -0.72501815022502;
   fWeightMatrix1to2[1][2] = 2.59421569220529;
   fWeightMatrix1to2[2][2] = -0.364296901435001;
   fWeightMatrix1to2[0][3] = -1.33997478766913;
   fWeightMatrix1to2[1][3] = 0.832348466684802;
   fWeightMatrix1to2[2][3] = -1.6217544143023;
   fWeightMatrix1to2[0][4] = -1.87058049760103;
   fWeightMatrix1to2[1][4] = 0.405709626439317;
   fWeightMatrix1to2[2][4] = -0.385344232947748;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.327409206075639;
   fWeightMatrix2to3[0][1] = -0.563505392026884;
   fWeightMatrix2to3[0][2] = -0.37175708762309;
   fWeightMatrix2to3[0][3] = -0.365057172731444;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
