inout:	 inout.cpp
	g++ -o inout.exe inout.cpp

ex1:	 example1.cpp
	g++ -o example1.exe example1.cpp

ex2:	 example2.cpp
	g++ -o example2.exe example2.cpp

ex3:	 example3.cpp
	g++ -o example3.exe example3.cpp

ex4:	 example4.cpp
	g++ -o example4.exe example4.cpp

ex5:	 example5.cpp
	g++ -o example5.exe example5.cpp
	
crea:	creation.cpp
	g++ -g -o creation.exe creation.cpp
	
leggi:	lecture.cpp
	g++ -g -o lecture.exe lecture.cpp

cleanext:
	rm *.txt

clean:	
	rm *~ *.txt *.exe core*
